knp_paginator:
    convert_exception: false
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: knp_sort
        sort_direction_name: knp_direction
        distinct: true
        filter_field_name: filterField
        filter_value_name: filterValue
        page_out_of_range: ignore
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'
