knp_paginator:
  default_options:
    page_name: page
    sort_field_name: knp_sort
    sort_direction_name: knp_direction
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
    sortable: '@KnpPaginator/Pagination/bootstrap_v5_bi_sortable_link.html.twig'
