framework:
    validation:
        email_validation_mode: html5

        # Contrôles côté serveur : contraintes Assert sur les entités.
        auto_mapping:
            App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
